# Site settings
author: A. Grant Schissler 
description: Personal website, publications, and stat blog
highlighter: pygments
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: /blog/:categories/:year/:month/:day/:title.html

twitter_username: gschissler
github_username:  grizant

# Build settings
markdown: kramdown
exclude: ["Rmd", ".DS_Store", "README.md"]
excerpt_separator: <!--more-->